#! /bin/bash

#usage in linuxmint: use startup application in start menu
#add your script to start up here


#mem
open https://mem.ai/home/added-by-me &

#tldr get entries
tldr -u

#aliCould sync
#aliyunpan sync start

#swap esc and capslock
sh ~/dotfiles/startup/swapEscCap.sh

#mount share
sh ~/dotfiles/startup/mountShare.sh
